### ISSUE TITLE
Why are you targeting "netcoreapp2.1" instead of "netstandard2.0"?

### ISSUE THREAD

**Issue by NikolayIT** [AlexPoint/SubtitlesParser#14]
I've managed to build the project successfully targeting .NET Standard.

[SubtitlesParser.1.4.7.nupkg.zip](https://github.com/AlexPoint/SubtitlesParser/files/3023028/SubtitlesParser.1.4.7.nupkg.zip)

Why do you target .NET Core App 2.1? It is more limiting.

**Comment by AlexPoint** [comment]
I haven't touched this library for quite some time now so I don't remember if there was a reason for using .NET Core.
If you manage to compile and run the tests with .NET Standard - indeed, I don't see any reason why .NET Standard wouldn't be enough - you can a pull request and I'll accept the changes.

**Comment by Anduin2017** [comment]
It was me who upgraded this project from .NET Framework to .NET Core. I didn't consider that you may use it in Xamarin or other areas.
