### ISSUE TITLE
Please remove all Console.WriteLine calls in the parsers

### ISSUE THREAD

**Issue by NikolayIT** [AlexPoint/SubtitlesParser#15]
Console.WriteLine is not the appropriate way to log debug information (example: https://github.com/AlexPoint/SubtitlesParser/blob/master/SubtitlesParser/Classes/Parsers/MicroDvdParser.cs#L77)

Not only it brings noise to the Console applicaitons, it also crashes when this code is ran in Windows Service environment.

**Comment by AlexPoint** [comment]
You're right, this "Console.WriteLine" statement is probably a remnant of my debugging.
It would be great if you can a pull request fixing this issue.
