### ISSUE TITLE
Parsing as srt returned no srt part

### ISSUE THREAD

**Issue by tuanbs** [AlexPoint/SubtitlesParser#19]
Hello developer, I got the following error when I parsed the SRT file:
```bash
System.FormatException
Message : Parsing as srt returned no srt part.
StackTrace :    at SubtitlesParser.Classes.Parsers.SrtParser.ParseStream(Stream srtStream, Encoding encoding)
```
I guess the SRT file is invalid or corrupt, but I when I use VLC player to play the video, VLC player still shows the subtitle from this SRT file. So I think it's a valid SRT file.

It worked with the other SRT files I have but not for this file. I attach the video and its SRT file for your reference. I also used another package called `node srt-to-vtt` to convert it, but I got the blank VTT file.

FYI, I use the tool called [SubtitleEdit](https://github.com/SubtitleEdit/subtitleedit) to create the SRT file for this video. Thanks in advance if there's any solution or workaround to fix this issue. 

[Archive.zip](https://github.com/AlexPoint/SubtitlesParser/files/3124000/Archive.zip)

**Comment by tuanbs** [comment]
sorry, issue is fixed by putting my conversion code outside of the `using` block. Somehow the FileStream returns empty content of the SRT file inside the `using` block. Please closed or deleted this issue. Thanks.

**Comment by AlexPoint** [comment]
Good to hear.
I'm closing this issue then.
