### ISSUE TITLE
Location data is lost in the WebVTT file

### ISSUE THREAD

**Issue by manikwwtc** [AlexPoint/SubtitlesParser#24]
The location data of the subtitle in the WebVTT is lost, how it can be retained while parsing for e.g. -

00:00:02.377 --> 00:00:06.423 **align:middle line:79% position:50% size:85%**

Attached a sample WebVTT file -

[Butterfly_Trees-final.vtt.txt](https://github.com/AlexPoint/SubtitlesParser/files/3867904/Butterfly_Trees-final.vtt.txt)

**Comment by AlexPoint** [comment]
Indeed, the first implementation of the subtitles parsers do not take into account the location, as only a few subtitles format support it.
To parse this information, you should add a location property to the formats which support it - WebVTT is one of them - and update the Parse() method.
I don't have time to code right now so you will have to do the changes yourself. 
I can publish a new nuget package after your pull request though.
