### ISSUE TITLE
How to convert SRT to VTT or vice versa?

### ISSUE THREAD

**Issue by tuanbs** [AlexPoint/SubtitlesParser#25]
Thanks for this nuget, very useful for me. Just wondering if it can convert SRT to VTT file or vice versa? For example:
```cs
var parser = new SubtitlesParser.Classes.Parsers.SubParser();
List<SubtitlesParser.Classes.SubtitleItem> subtitleItems = null;
using (var fileStream = File.OpenRead(pathToSrtFile))
{
	subtitleItems = parser.ParseStream(fileStream);
}
```
Then how to write out `subtitleItems` into `srt` or `vtt` files like `srtFormat.srt` or `vttFormat.vtt`?

At the moment I'm using the Node library named `SrtToVtt.js` to convert `srt` to `vtt` but DotNet Core 3 marks it as `Obsolete`. So I'm looking for another approach to convert it. Thank you.

**Comment by AlexPoint** [comment]
This library does not support the writing of subtitles files.
However, it should not be very difficult to add a write method for the different formats (you may have some missing information for specific format though). Once you have those methods, you can easily convert subtitles between different formats (read in a given format and write in another).
I don't have time to do it right now but maybe later during the year. Or even better if you can do a pull request with those changes.
