### ISSUE TITLE
Dual license?

### ISSUE THREAD

**Issue by jmpease** [AlexPoint/SubtitlesParser#3]
Any chance you'd consider dual-licensing under something more permissive, such as an MIT license?  I came across this library and think it may be an ideal fit for a current need.  Unfortunately, given the gray area around dynamic linkage of GPL libraries (IANAL) I'm afraid it is not something we'll be able to use considering our current license model.

Will certainly fork/contribute any modifications/extensions we distribute if this is something you're willing to do.

**Comment by AlexPoint** [comment]
I just changed the license to MIT; there was no specific reason to use GPL as far as I am concerned.
