### ISSUE TITLE
Updated NuGet

### ISSUE THREAD

**Issue by baltuonis** [AlexPoint/SubtitlesParser#33]
Hey, 

Are you going to publish the latest NuGet release?
The actual one is out of date (does not have Writer classes)

Also, you have a null reference exception in SRT parser.
Line 84. Need to add `                            item.PlaintextLines ??= new List<string>();`

P.S. Great library.

**Comment by AlexPoint** [comment]
Indeed, the last PR is not published on nuget. 
I'll do it by the end of the week. Also, I'll have a look at the issue you mention. 
Keep you posted

**Comment by AlexPoint** [comment]
The fix has been pushed and the nuget package is published with the latest changes (v1.5.0 - https://www.nuget.org/packages/SubtitlesParser/).
Have fun!
