### ISSUE TITLE
TTML Files from Youtube fail

### ISSUE THREAD

**Issue by Lone-Coder** [AlexPoint/SubtitlesParser#4]
Run this (with http://rg3.github.io/youtube-dl/) to get a TTML file that fails with a null reference.

`youtube-dl.exe --write-info-json --write-auto-sub --sub-lang en --sub-format ttml -o %(id)s.mp4 -f mp4 https://www.youtube.com/watch?v=kYB8IZa5AuE`

`System.ArgumentNullException was unhandled by user code
  HResult=-2147467261
  Message=Value cannot be null.
Parameter name: ns
  ParamName=ns
  Source=System.Xml.Linq
  StackTrace:
       at System.Xml.Linq.XNamespace.op_Addition(XNamespace ns, String localName)
       at SubtitlesParser.Classes.Parsers.TtmlParser.ParseStream(Stream xmlStream, Encoding encoding)
`

**Comment by Lone-Coder** [comment]
Here's a version that works with youtube.

I added support for the default namespace and changed the way the times are being parsed.

`using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml;
using System.Xml.Linq;

namespace SubtitlesParser.Classes.Parsers
{
    public class TtmlParser:ISubtitlesParser
    {
        public List<SubtitleItem> ParseStream(Stream xmlStream, Encoding encoding)
        {
            // rewind the stream
            xmlStream.Position = 0;
            var items = new List<SubtitleItem>();

            // parse xml stream
            var xElement = XElement.Load(xmlStream);
            XNamespace tt = xElement.GetNamespaceOfPrefix("tt");
            if (tt == null)
                tt = xElement.GetDefaultNamespace();

            if (xElement != null)
            {
                var nodeList = xElement.Descendants(tt + "p").ToList();

                if (nodeList != null)
                {
                    for (var i = 0; i < nodeList.Count; i++)
                    {
                        var node = nodeList[i];
                        try
                        {
                            var reader = node.CreateReader();
                            reader.MoveToContent();
                            var beginString = node.Attribute("begin").Value.Replace("t", "");
                            long startTicks = ParseTimecode(beginString);
                            var endString = node.Attribute("end").Value.Replace("t", "");
                            long endTicks = ParseTimecode(endString);
                            var text = reader.ReadInnerXml().Replace("<tt:", "<").Replace("</tt:", "</").Replace(string.Format(@" xmlns:tt=""{0}""", tt), "").Replace(string.Format(@" xmlns=""{0}""", tt), "");

                            items.Add(new SubtitleItem()
                            {
                                StartTime = (int)(startTicks),
                                EndTime = (int)(endTicks),
                                Lines = new List<string>() { text }
                            });
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine("Exception raised when parsing xml node {0}: {1}", node, ex);
                        }
                    }  
                }
            }

            if (items.Any())
            {
                return items;
            }
            else
            {
                throw new ArgumentException("Stream is not in a valid TTML format, or represents empty subtitles");
            }
        }

        /// <summary>
        /// Takes an SRT timecode as a string and parses it into a double (in seconds). A SRT timecode reads as follows: 
        /// 00:00:20,000
        /// </summary>
        /// <param name="s">The timecode to parse</param>
        /// <returns>The parsed timecode as a TimeSpan instance. If the parsing was unsuccessful, -1 is returned (subtitles should never show)</returns>
        private int ParseTimecode(string s)
        {
            TimeSpan result;

            if (TimeSpan.TryParse(s, out result))
            {
                var nbOfMs = (int)result.TotalMilliseconds;
                return nbOfMs;
            }
            else
            {
                return -1;
            }
        }
    }
}
`

**Comment by AlexPoint** [comment]
Indeed, the timespans were not parsed correctly.
It's been fixed here: https://github.com/AlexPoint/SubtitlesParser/commit/fb0c43219bef994299c8dfd2589d1b45834f3996
Thanks for the code; don't hesitate to do a pull request next time ;)
A new nuget package (1.4.7 has been released with those changes)
