### ISSUE TITLE
Package is not available on Nuget

### ISSUE THREAD

**Issue by andreencar** [AlexPoint/SubtitlesParser#6]
Hey, I was trying to install your library but apparently, it does not appear on Nuget... Is there any reason why?

**Comment by AlexPoint** [comment]
What you describe is weird.
I can see it on nuget: https://www.nuget.org/packages/SubtitlesParser/ 
Do you have troubles downloading the package?

**Comment by markwalsh-liverpool** [comment]
It is available on my Nuget feed.

**Comment by Anduin2017** [comment]
Ths nuget version seems to be very old and not the .NET standard build.

**Comment by AlexPoint** [comment]
Indeed, the nuget version does not include your last pull request with the .NET standard build.
I will need some time to reinstall everything and push the updated nuget package.

**Comment by Anduin2017** [comment]
Hi @AlexPoint . You only need to install one thing, the latest `.NET Core SDK` from [here](http://dot.net). 
 It only requires about 300MB space. 

After installing it, try execute the following command on the root folder of this project:

```bash
$ dotnet pack -c Release
```

And you will find the built package here.

> /bin/Release/Yourpackage.nupkg

Please upload it [here](https://nuget.org).

![Untitled](https://user-images.githubusercontent.com/19531547/56706150-e5ade680-674e-11e9-9503-1e84714cd790.png)

And we all can download and use it.

Thank you very much for uploading that!

**Comment by AlexPoint** [comment]
Thanks for the instructions @Anduin2017! 
It was very helpful since I haven't touched nuget and VS for quite some time now.
SubtitlesParser 1.4.8 is now available on nuget with your latest contributions: [https://www.nuget.org/packages/SubtitlesParser/](https://www.nuget.org/packages/SubtitlesParser/)
Please confirm that everything works as expected and enjoy.
